// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from "react";
import accessFactory from "@/access";
import { useGlobalStore } from "@/stores";

import { AccessContext } from "./context";

function Provider(props) {
  const { oauth } = useGlobalStore();
  const access = React.useMemo(() => accessFactory(oauth), [oauth]);
  return (
    <AccessContext.Provider value={access}>
      {props.children?.children}
    </AccessContext.Provider>
  );
}

export function accessProvider(container) {
  return <Provider>{container}</Provider>;
}
